version: "3"
services:
  postgres:
    image: "postgres:15.6"
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sistema-e-learning