package pe.devstream.controller.advice;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum DetalleErrorEnum {
  // CODIGOS DE ERRORES, LINEAMIENTOS
  ERROR_NO_AUTORIZADO("001"),
  ERROR_DATA_BASE("002"),
  ERROR_GENERICO("003"),
  RUTA_NO_ENCONTRADA("004"),
  ERROR_FORMATO_CABECERA("005"),
  ERROR_VALIDACION_CABECERA("006"),
  ERROR_FORMATO_REQUEST("007"),
  ERROR_VALIDACION_REQUEST("008"),
  ERROR_DUPLICACION_REGISTRO("009"),

  // PREFIJOS DE TIPOS DE ERROR, LINEAMIENTOS
  PREFIJO_ERROR_FUNCIONAL("F"),
  PREFIJO_ERROR_SISTEMA("S"),

  PREFIJO_ERROR_CANAL_NEGOCIO("NE"),
  PREFIJO_ERROR_CANAL_GENERICO("GE"),

  PREFIJO_ERROR_COMPONENTE_MICROSERVICIO("MS"),
  PREFIJO_ERROR_COMPONENTE_EXTERNO("SE"),
  PREFIJO_ERROR_COMPONENTE_DATABASE("BD"),

  // TIPOS DE ERRORES
  FUNCIONAL("FUNCIONAL"),
  SISTEMA("SISTEMA");

  private final String code;
}
